/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-05-09 18:50:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>RRIT — Add Student</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary: #4CAF50; --primary-dark: #45a049;\n");
      out.write("            --accent: #6c63ff;\n");
      out.write("            --bg: #f0f4f8; --card: #ffffff;\n");
      out.write("            --text: #1a1a2e; --muted: #64748b; --border: #e2e8f0;\n");
      out.write("            --error: #ef4444;\n");
      out.write("        }\n");
      out.write("        * { margin:0; padding:0; box-sizing:border-box; }\n");
      out.write("        body { font-family:'Inter',Arial,sans-serif; background:var(--bg); min-height:100vh; }\n");
      out.write("\n");
      out.write("        /* NAV */\n");
      out.write("        .top-nav {\n");
      out.write("            background:#1a1a2e; padding:14px 32px;\n");
      out.write("            display:flex; align-items:center; justify-content:space-between; flex-wrap:wrap; gap:12px;\n");
      out.write("        }\n");
      out.write("        .nav-brand { color:#fff; font-size:1.1rem; font-weight:800; }\n");
      out.write("        .nav-links { display:flex; gap:8px; flex-wrap:wrap; }\n");
      out.write("        .nav-links a {\n");
      out.write("            padding:7px 16px; border-radius:8px; text-decoration:none;\n");
      out.write("            font-size:0.85rem; font-weight:600; transition:all 0.2s;\n");
      out.write("        }\n");
      out.write("        .nav-links a.active { background:var(--primary); color:#fff; }\n");
      out.write("        .nav-links a.leave-link { background:linear-gradient(135deg,#6c63ff,#43e97b); color:#fff; }\n");
      out.write("        .nav-links a.secondary { color:#a0aec0; border:1px solid #2d3748; }\n");
      out.write("        .nav-links a.secondary:hover { color:#fff; border-color:#4a5568; }\n");
      out.write("\n");
      out.write("        /* INFO BANNER */\n");
      out.write("        .info-banner {\n");
      out.write("            background:linear-gradient(135deg,#6c63ff15,#43e97b10);\n");
      out.write("            border-bottom:1px solid #6c63ff33;\n");
      out.write("            padding:12px 32px;\n");
      out.write("            display:flex; align-items:center; gap:10px; flex-wrap:wrap;\n");
      out.write("        }\n");
      out.write("        .info-banner span { font-size:0.88rem; color:#4a5568; }\n");
      out.write("        .info-banner strong { color:#6c63ff; }\n");
      out.write("\n");
      out.write("        /* FORM */\n");
      out.write("        .page-wrap { display:flex; justify-content:center; padding:40px 20px; }\n");
      out.write("        .container {\n");
      out.write("            width:100%; max-width:580px;\n");
      out.write("            background:var(--card); padding:40px 36px;\n");
      out.write("            border-radius:16px; box-shadow:0 4px 24px rgba(0,0,0,0.08);\n");
      out.write("            border:1px solid var(--border);\n");
      out.write("        }\n");
      out.write("        .container-header { text-align:center; margin-bottom:32px; }\n");
      out.write("        .container-header .icon { font-size:2.5rem; display:block; margin-bottom:10px; }\n");
      out.write("        h2 { font-size:1.5rem; color:var(--text); font-weight:800; }\n");
      out.write("        .container-header p { color:var(--muted); font-size:0.88rem; margin-top:6px; }\n");
      out.write("\n");
      out.write("        .section-divider {\n");
      out.write("            display:flex; align-items:center; gap:12px; margin:24px 0 20px;\n");
      out.write("        }\n");
      out.write("        .section-divider::before, .section-divider::after {\n");
      out.write("            content:''; flex:1; height:1px; background:var(--border);\n");
      out.write("        }\n");
      out.write("        .section-divider span { color:var(--muted); font-size:0.78rem; font-weight:700; text-transform:uppercase; letter-spacing:0.8px; white-space:nowrap; }\n");
      out.write("\n");
      out.write("        .form-row { display:flex; gap:14px; }\n");
      out.write("        .form-group { margin-bottom:18px; flex:1; }\n");
      out.write("        label {\n");
      out.write("            display:block; margin-bottom:7px;\n");
      out.write("            font-size:0.8rem; font-weight:700; color:var(--muted);\n");
      out.write("            text-transform:uppercase; letter-spacing:0.5px;\n");
      out.write("        }\n");
      out.write("        label .required { color:var(--error); margin-left:2px; }\n");
      out.write("        input[type=\"text\"], input[type=\"email\"], input[type=\"password\"], input[type=\"tel\"], select {\n");
      out.write("            width:100%; padding:11px 14px;\n");
      out.write("            border:1.5px solid var(--border); border-radius:10px;\n");
      out.write("            font-family:'Inter',sans-serif; font-size:0.92rem; color:var(--text);\n");
      out.write("            transition:all 0.2s; outline:none; background:#fafbfc;\n");
      out.write("            -webkit-appearance:none;\n");
      out.write("        }\n");
      out.write("        input:focus, select:focus {\n");
      out.write("            border-color:var(--primary); background:#fff;\n");
      out.write("            box-shadow:0 0 0 3px rgba(76,175,80,0.12);\n");
      out.write("        }\n");
      out.write("        input::placeholder { color:#b0bac5; }\n");
      out.write("        select option { background:#fff; color:var(--text); }\n");
      out.write("\n");
      out.write("        .pw-wrap { position:relative; }\n");
      out.write("        .toggle-pw { position:absolute; right:12px; top:50%; transform:translateY(-50%); background:none; border:none; cursor:pointer; color:var(--muted); font-size:1rem; }\n");
      out.write("\n");
      out.write("        .note-box {\n");
      out.write("            background:rgba(108,99,255,0.07); border:1px solid rgba(108,99,255,0.25);\n");
      out.write("            border-radius:10px; padding:12px 16px; margin-bottom:20px;\n");
      out.write("            font-size:0.84rem; color:#5a52d5; line-height:1.5;\n");
      out.write("            display:flex; align-items:flex-start; gap:8px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        button[type=\"submit\"] {\n");
      out.write("            width:100%; padding:13px;\n");
      out.write("            background:linear-gradient(135deg,var(--primary),var(--primary-dark));\n");
      out.write("            color:white; border:none; border-radius:10px;\n");
      out.write("            cursor:pointer; font-size:0.95rem; font-weight:700;\n");
      out.write("            font-family:'Inter',sans-serif; transition:all 0.2s; margin-top:4px;\n");
      out.write("        }\n");
      out.write("        button[type=\"submit\"]:hover { transform:translateY(-2px); box-shadow:0 6px 20px rgba(76,175,80,0.35); }\n");
      out.write("\n");
      out.write("        .bottom-links {\n");
      out.write("            display:flex; justify-content:center; gap:24px; margin-top:22px; flex-wrap:wrap;\n");
      out.write("        }\n");
      out.write("        .bottom-links a {\n");
      out.write("            color:var(--muted); text-decoration:none; font-size:0.88rem; font-weight:500;\n");
      out.write("            display:flex; align-items:center; gap:5px; transition:color 0.2s;\n");
      out.write("        }\n");
      out.write("        .bottom-links a:hover { color:var(--text); }\n");
      out.write("        .bottom-links a.highlight { color:#6c63ff; font-weight:700; }\n");
      out.write("\n");
      out.write("        /* Success toast */\n");
      out.write("        .toast {\n");
      out.write("            position:fixed; bottom:24px; right:24px; z-index:1000;\n");
      out.write("            background:#4CAF50; color:#fff; font-weight:700;\n");
      out.write("            padding:14px 24px; border-radius:12px;\n");
      out.write("            box-shadow:0 8px 30px rgba(76,175,80,0.4);\n");
      out.write("            transform:translateY(80px); opacity:0;\n");
      out.write("            transition:all 0.4s; font-family:'Inter',sans-serif; font-size:0.9rem;\n");
      out.write("        }\n");
      out.write("        .toast.show { transform:translateY(0); opacity:1; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <nav class=\"top-nav\">\n");
      out.write("        <div class=\"nav-brand\">🎓 RRIT — Student Management</div>\n");
      out.write("        <div class=\"nav-links\">\n");
      out.write("            <a href=\"index.jsp\" class=\"active\">Add Student</a>\n");
      out.write("            <a href=\"view.jsp\" class=\"secondary\">View Students</a>\n");
      out.write("            <a href=\"leave-system/index.html\" class=\"leave-link\">📋 Leave & Attendance</a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"info-banner\">\n");
      out.write("        <span>ℹ️ Students added here are saved to the <strong>MySQL database</strong> AND automatically registered for the <strong>Leave & Attendance Portal</strong>. They can login to the leave portal using their Roll No. and password set below.</span>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"page-wrap\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"container-header\">\n");
      out.write("                <span class=\"icon\">🧑‍🎓</span>\n");
      out.write("                <h2>Add New Student</h2>\n");
      out.write("                <p>Student will be saved to the server database and can login to the Leave Portal</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"note-box\">\n");
      out.write("                🔑 The <strong>Roll Number</strong> and <strong>Password</strong> you set here will be used by the student to login to the <strong>Leave & Attendance System</strong>.\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <form id=\"addStudentForm\" action=\"student\" method=\"post\" onsubmit=\"saveToLeaveSystem(event)\">\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"insert\">\n");
      out.write("\n");
      out.write("                <!-- Basic Info -->\n");
      out.write("                <div class=\"section-divider\"><span>Basic Information</span></div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"firstName\">First Name <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"firstName\" name=\"firstName\" placeholder=\"Ayush\" required>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"lastName\">Last Name <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"lastName\" name=\"lastName\" placeholder=\"Sharma\" required>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Hidden combined name for old servlet -->\n");
      out.write("                <input type=\"hidden\" id=\"name\" name=\"name\">\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"email\">Email Address <span class=\"required\">*</span></label>\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"student@college.edu\" required>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"rollNo\">Roll Number <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"rollNo\" name=\"rollNo\" placeholder=\"CS2024001\" required>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"usn\">USN <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"usn\" name=\"usn\" placeholder=\"e.g. 1RR21CS001\" required\n");
      out.write("                            style=\"text-transform:uppercase;\"\n");
      out.write("                            title=\"University Serial Number assigned by the institution\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"phone\">Phone Number</label>\n");
      out.write("                    <input type=\"tel\" id=\"phone\" name=\"phone\" placeholder=\"10-digit mobile number\" maxlength=\"10\">\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Academic Info -->\n");
      out.write("                <div class=\"section-divider\"><span>Academic Details</span></div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"course\">Course <span class=\"required\">*</span></label>\n");
      out.write("                    <select id=\"course\" name=\"course\" required>\n");
      out.write("                        <option value=\"\">Select Course</option>\n");
      out.write("                        <option>B.Tech CSE</option>\n");
      out.write("                        <option>B.Tech IT</option>\n");
      out.write("                        <option>B.Tech ECE</option>\n");
      out.write("                        <option>B.Tech Mechanical</option>\n");
      out.write("                        <option>BCA</option>\n");
      out.write("                        <option>MCA</option>\n");
      out.write("                        <option>MBA</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"year\">Year <span class=\"required\">*</span></label>\n");
      out.write("                        <select id=\"year\" name=\"year\" required>\n");
      out.write("                            <option value=\"\">Year</option>\n");
      out.write("                            <option>1st Year</option>\n");
      out.write("                            <option>2nd Year</option>\n");
      out.write("                            <option>3rd Year</option>\n");
      out.write("                            <option>4th Year</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"section\">Section <span class=\"required\">*</span></label>\n");
      out.write("                        <input type=\"text\" id=\"section\" name=\"section\" placeholder=\"e.g. A\" required>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Leave Portal Password -->\n");
      out.write("                <div class=\"section-divider\"><span>Leave Portal Login Password</span></div>\n");
      out.write("\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"password\">Set Password <span class=\"required\">*</span></label>\n");
      out.write("                    <div class=\"pw-wrap\">\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Min 6 characters\" required minlength=\"6\">\n");
      out.write("                        <button type=\"button\" class=\"toggle-pw\" onclick=\"togglePw()\">👁</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <button type=\"submit\">Add Student & Register for Leave Portal →</button>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <div class=\"bottom-links\">\n");
      out.write("                <a href=\"view.jsp\">📋 View All Students</a>\n");
      out.write("                <a href=\"leave-system/index.html\" class=\"highlight\">📝 Leave System →</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"toast\" id=\"toast\">✅ Student added to DB and Leave Portal!</div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        function togglePw() {\n");
      out.write("            const inp = document.getElementById('password');\n");
      out.write("            inp.type = inp.type === 'password' ? 'text' : 'password';\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        function saveToLeaveSystem(e) {\n");
      out.write("            // Set combined name for the servlet\n");
      out.write("            const first = document.getElementById('firstName').value.trim();\n");
      out.write("            const last  = document.getElementById('lastName').value.trim();\n");
      out.write("            document.getElementById('name').value = first + ' ' + last;\n");
      out.write("\n");
      out.write("            const rollNo   = document.getElementById('rollNo').value.trim().toUpperCase();\n");
      out.write("            const usn      = document.getElementById('usn').value.trim().toUpperCase();\n");
      out.write("            const email    = document.getElementById('email').value.trim().toLowerCase();\n");
      out.write("            const course   = document.getElementById('course').value;\n");
      out.write("            const year     = document.getElementById('year').value;\n");
      out.write("            const section  = document.getElementById('section').value.trim().toUpperCase();\n");
      out.write("            const phone    = document.getElementById('phone').value.trim();\n");
      out.write("            const password = document.getElementById('password').value;\n");
      out.write("\n");
      out.write("            // Load existing students from localStorage\n");
      out.write("            const students = JSON.parse(localStorage.getItem('eduLeave_students') || '[]');\n");
      out.write("\n");
      out.write("            // Check for duplicate roll\n");
      out.write("            const dupRoll = students.find(s => s.rollNo === rollNo);\n");
      out.write("            if (dupRoll) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                alert('⚠️ A student with Roll No. \"' + rollNo + '\" is already registered in the Leave Portal.');\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            // Save this student to localStorage so they can login to the leave portal\n");
      out.write("            const newStudent = {\n");
      out.write("                id: Date.now().toString(),\n");
      out.write("                firstName: first,\n");
      out.write("                lastName: last,\n");
      out.write("                name: first + ' ' + last,\n");
      out.write("                rollNo, usn, email, course, year, section, phone, password,\n");
      out.write("                registeredAt: new Date().toISOString(),\n");
      out.write("                addedByAdmin: true,   // flag: registered via admin (index.jsp)\n");
      out.write("                profileComplete: false // student must fill extra details on first login\n");
      out.write("            };\n");
      out.write("            students.push(newStudent);\n");
      out.write("            localStorage.setItem('eduLeave_students', JSON.stringify(students));\n");
      out.write("\n");
      out.write("            // Show toast briefly (form will submit and page will reload)\n");
      out.write("            const toast = document.getElementById('toast');\n");
      out.write("            toast.classList.add('show');\n");
      out.write("            // Allow form to continue submitting to servlet\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
