/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2026-05-09 18:51:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.student.dao.StudentDAO;
import com.student.model.Student;
import java.util.List;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.student.dao.StudentDAO");
    _jspx_imports_classes.add("com.student.model.Student");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>RRIT — View Students</title>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        :root {\n");
      out.write("            --primary: #4CAF50;\n");
      out.write("            --accent: #6c63ff;\n");
      out.write("            --bg: #f0f4f8;\n");
      out.write("            --card: #ffffff;\n");
      out.write("            --text: #1a1a2e;\n");
      out.write("            --muted: #64748b;\n");
      out.write("            --border: #e2e8f0;\n");
      out.write("        }\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\n");
      out.write("        body { font-family: 'Inter', Arial, sans-serif; background: var(--bg); min-height: 100vh; }\n");
      out.write("\n");
      out.write("        /* ---- NAV ---- */\n");
      out.write("        .top-nav {\n");
      out.write("            background: #1a1a2e;\n");
      out.write("            padding: 14px 32px;\n");
      out.write("            display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px;\n");
      out.write("        }\n");
      out.write("        .nav-brand { color: #fff; font-size: 1.1rem; font-weight: 800; display: flex; align-items: center; gap: 10px; }\n");
      out.write("        .nav-links { display: flex; gap: 8px; flex-wrap: wrap; }\n");
      out.write("        .nav-links a {\n");
      out.write("            padding: 7px 16px; border-radius: 8px; text-decoration: none;\n");
      out.write("            font-size: 0.85rem; font-weight: 600; transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .nav-links a.active { background: var(--primary); color: #fff; }\n");
      out.write("        .nav-links a.leave-link { background: linear-gradient(135deg, #6c63ff, #43e97b); color: #fff; }\n");
      out.write("        .nav-links a.secondary { color: #a0aec0; border: 1px solid #2d3748; }\n");
      out.write("        .nav-links a.secondary:hover { color: #fff; border-color: #4a5568; }\n");
      out.write("\n");
      out.write("        /* ---- BANNER ---- */\n");
      out.write("        .leave-banner {\n");
      out.write("            background: linear-gradient(135deg, #6c63ff22, #43e97b18);\n");
      out.write("            border-bottom: 1px solid #6c63ff44;\n");
      out.write("            padding: 14px 32px;\n");
      out.write("            display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px;\n");
      out.write("        }\n");
      out.write("        .leave-banner p { font-size: 0.9rem; color: #4a5568; font-weight: 500; }\n");
      out.write("        .leave-banner p strong { color: #6c63ff; }\n");
      out.write("        .banner-btn {\n");
      out.write("            padding: 8px 18px; border-radius: 8px; font-size: 0.85rem;\n");
      out.write("            font-weight: 700; text-decoration: none; transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .banner-btn.primary { background: #6c63ff; color: #fff; }\n");
      out.write("        .banner-btn.primary:hover { background: #5a52d5; }\n");
      out.write("\n");
      out.write("        /* ---- MAIN ---- */\n");
      out.write("        .page-wrap { padding: 40px 32px; max-width: 1100px; margin: 0 auto; }\n");
      out.write("\n");
      out.write("        .page-header {\n");
      out.write("            display: flex; align-items: center; justify-content: space-between;\n");
      out.write("            flex-wrap: wrap; gap: 16px; margin-bottom: 28px;\n");
      out.write("        }\n");
      out.write("        .page-header h2 { font-size: 1.6rem; font-weight: 800; color: var(--text); }\n");
      out.write("        .page-header p { color: var(--muted); font-size: 0.9rem; margin-top: 4px; }\n");
      out.write("        .header-actions { display: flex; gap: 10px; flex-wrap: wrap; }\n");
      out.write("        .btn {\n");
      out.write("            padding: 10px 20px; border-radius: 10px; font-size: 0.88rem; font-weight: 700;\n");
      out.write("            text-decoration: none; transition: all 0.2s; display: inline-block; border: none; cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .btn-green { background: var(--primary); color: #fff; }\n");
      out.write("        .btn-green:hover { background: #45a049; }\n");
      out.write("        .btn-purple { background: #6c63ff; color: #fff; }\n");
      out.write("        .btn-purple:hover { background: #5a52d5; }\n");
      out.write("        .btn-outline { background: #fff; color: var(--muted); border: 1.5px solid var(--border); }\n");
      out.write("        .btn-outline:hover { color: var(--text); border-color: #aaa; }\n");
      out.write("\n");
      out.write("        /* ---- TABLE ---- */\n");
      out.write("        .table-card {\n");
      out.write("            background: var(--card); border-radius: 16px;\n");
      out.write("            border: 1px solid var(--border);\n");
      out.write("            box-shadow: 0 2px 12px rgba(0,0,0,0.06);\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        table { width: 100%; border-collapse: collapse; }\n");
      out.write("        thead tr { background: #f8fafc; }\n");
      out.write("        th {\n");
      out.write("            padding: 14px 20px; text-align: left;\n");
      out.write("            font-size: 0.78rem; font-weight: 700; color: var(--muted);\n");
      out.write("            text-transform: uppercase; letter-spacing: 0.6px;\n");
      out.write("            border-bottom: 1px solid var(--border);\n");
      out.write("        }\n");
      out.write("        td { padding: 16px 20px; border-bottom: 1px solid var(--border); font-size: 0.92rem; color: var(--text); vertical-align: middle; }\n");
      out.write("        tbody tr:last-child td { border-bottom: none; }\n");
      out.write("        tbody tr:hover td { background: #f8fafc; }\n");
      out.write("\n");
      out.write("        .student-id { font-size: 0.8rem; color: var(--muted); font-weight: 600; }\n");
      out.write("        .course-badge {\n");
      out.write("            display: inline-block; padding: 4px 12px; border-radius: 50px;\n");
      out.write("            background: rgba(76,175,80,0.1); color: var(--primary);\n");
      out.write("            font-size: 0.8rem; font-weight: 600; border: 1px solid rgba(76,175,80,0.2);\n");
      out.write("        }\n");
      out.write("        .actions-cell { display: flex; gap: 8px; }\n");
      out.write("        .act-btn {\n");
      out.write("            padding: 5px 14px; border-radius: 7px; font-size: 0.8rem; font-weight: 600;\n");
      out.write("            text-decoration: none; border: none; cursor: pointer; transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .act-leave { background: rgba(108,99,255,0.1); color: #6c63ff; border: 1px solid rgba(108,99,255,0.25); }\n");
      out.write("        .act-leave:hover { background: #6c63ff; color: #fff; }\n");
      out.write("\n");
      out.write("        .empty-row td { text-align: center; padding: 48px; color: var(--muted); font-size: 1rem; }\n");
      out.write("\n");
      out.write("        .bottom-links {\n");
      out.write("            display: flex; gap: 16px; margin-top: 24px; flex-wrap: wrap;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Nav -->\n");
      out.write("    <nav class=\"top-nav\">\n");
      out.write("        <div class=\"nav-brand\">🎓 RRIT — Student Management</div>\n");
      out.write("        <div class=\"nav-links\">\n");
      out.write("            <a href=\"index.jsp\" class=\"secondary\">Add Student</a>\n");
      out.write("            <a href=\"view.jsp\" class=\"active\">View Students</a>\n");
      out.write("            <a href=\"leave-system/index.html\" class=\"leave-link\">📋 Leave & Attendance System</a>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Leave Banner -->\n");
      out.write("    <div class=\"leave-banner\">\n");
      out.write("        <p>🔗 Connected to <strong>EduLeave</strong> — Click \"View Leaves\" next to any student to see their leave history.</p>\n");
      out.write("        <a href=\"leave-system/hod-portal.html\" class=\"banner-btn primary\">HOD Portal →</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"page-wrap\">\n");
      out.write("        <div class=\"page-header\">\n");
      out.write("            <div>\n");
      out.write("                <h2>All Students</h2>\n");
      out.write("                <p>Students registered in the database via the server-side system</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"header-actions\">\n");
      out.write("                <a href=\"leave-system/student-register.html\" class=\"btn btn-purple\">📝 Leave Registration</a>\n");
      out.write("                <a href=\"index.jsp\" class=\"btn btn-green\">+ Add Student</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"table-card\">\n");
      out.write("            ");

                StudentDAO studentDAO = new StudentDAO();
                List<Student> students = studentDAO.selectAllStudents();
            
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>ID</th>\n");
      out.write("                        <th>Name</th>\n");
      out.write("                        <th>Email</th>\n");
      out.write("                        <th>Course</th>\n");
      out.write("                        <th>Actions</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");
 if (students == null || students.isEmpty()) { 
      out.write("\n");
      out.write("                    <tr class=\"empty-row\"><td colspan=\"5\">📭 No students found. <a href=\"index.jsp\">Add the first student →</a></td></tr>\n");
      out.write("                    ");
 } else { 
      out.write("\n");
      out.write("                    ");
 for (Student student : students) { 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td><span class=\"student-id\">#");
      out.print( student.getId() );
      out.write("</span></td>\n");
      out.write("                        <td><strong>");
      out.print( student.getName() );
      out.write("</strong></td>\n");
      out.write("                        <td>");
      out.print( student.getEmail() );
      out.write("</td>\n");
      out.write("                        <td><span class=\"course-badge\">");
      out.print( student.getCourse() );
      out.write("</span></td>\n");
      out.write("                        <td>\n");
      out.write("                            <div class=\"actions-cell\">\n");
      out.write("                                <a href=\"leave-system/hod-portal.html\" class=\"act-btn act-leave\">📋 View Leaves</a>\n");
      out.write("                            </div>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"bottom-links\">\n");
      out.write("            <a href=\"index.jsp\" class=\"btn btn-outline\">← Add New Student</a>\n");
      out.write("            <a href=\"leave-system/index.html\" class=\"btn btn-purple\">Open Leave System →</a>\n");
      out.write("            <a href=\"leave-system/teacher-portal.html\" class=\"btn btn-outline\">👩‍🏫 Teacher Portal</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
